apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-microservice
  labels:
    app: delivery-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-microservice
  template:
    metadata:
      labels:
        app: delivery-microservice
    spec:
      containers:
        - name: delivery-microservice
          image: juanhoyos/microservice:delivery-v2
          ports:
            - containerPort: 8087
          env:
            - name: SERVER_PORT
              value: "8087"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: password
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: url
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"
